{
  "openapi":"3.0.2",
  "info": {
    "title":"NPSer",
    "version":"1.0",
    "license": {
      "name": "MIT",
      "url": "https://raw.githubusercontent.com/DiegoVictor/NPSer/master/LICENSE"
    }
  },
  "servers": [
    {
      "url":"http://localhost:3333/v1"
    }
  ],
  "paths": {
    "/users": {
      "post": {
        "tags": ["Users"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "title": "User",
                "required": [
                  "name",
                  "email"
                ],
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "name": "John Doe",
                "email": "johndoe@example.com.br"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Create a new user",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "example": {
                  "id": "34a7d67b-1191-468f-9187-3911cf8396b2",
                  "name": "John Doe",
                  "email": "johndoe@example.com.br",
                  "created_at": "2021-08-29T02:06:06.000Z"
                }
              }
            }
          },
          "400": {
            "description": "User already exists",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 400,
                  "error": "Bad Request",
                  "message": "User already exists",
                  "code": 140,
                  "docs": "https://github.com/DiegoVictor/npser#errors-reference"
                }
              }
            }
          }
        }
      }
    },
    "/surveys": {
      "get": {
        "tags": ["Surveys"],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "required": false,
            "schema": {
              "type": "integer"
            },
            "example": 1
          }
        ],
        "responses": {
          "200": {
            "description": "Lists surveys",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Survey"
                  }
                },
                "example": [
                  {
                    "id": "24d47172-8ddb-4281-af19-e0d5bda7c76e",
                    "title": "Internal Division Consultant",
                    "description": "Saepe recusandae vitae velit asperiores vel consequuntur ratione quam.",
                    "created_at": "2021-08-29T15:29:03.000Z"
                  }
                ]
              }
            },
            "headers": {
              "X-Total-Count": {
                "description": "Total number of registries in the database",
                "schema": {
                  "type": "integer"
                }
              },
              "Link": {
                "description": "Next, Previous, First and Last page's urls",
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["Surveys"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "title": "Survey",
                "required": [
                  "title",
                  "description"
                ],
                "properties": {
                  "title": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "title": "Internal Division Consultant",
                "description": "Saepe recusandae vitae velit asperiores vel consequuntur ratione quam."
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Create a new survey",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Survey"
                },
                "example": {
                  "id": "24d47172-8ddb-4281-af19-e0d5bda7c76e",
                  "title": "Internal Division Consultant",
                  "description": "Saepe recusandae vitae velit asperiores vel consequuntur ratione quam.",
                  "created_at": "2021-08-29T15:29:03.000Z"
                }
              }
            }
          }
        }
      }
    },
    "/send_mail": {
      "post": {
        "tags": ["NPS"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "title": "NPS",
                "required": [
                  "survey_id",
                  "email"
                ],
                "properties": {
                  "survey_id": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "email": "johndoe@example.com.br",
                "survey_id": "24d47172-8ddb-4281-af19-e0d5bda7c76e"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Send the NPS to provided user",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string",
                  "properties": {
                    "id": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "id": "c71cac0d-cb96-4c0d-884b-a66abd2b1e11"
                }
              }
            }
          },
          "400": {
            "description": "User or survey does not exists",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "examples": {
                  "User does not exists": {
                    "value": {
                      "statusCode": 400,
                      "error": "Bad Request",
                      "message": "User does not exists",
                      "code": 240,
                      "docs": "https://github.com/DiegoVictor/npser#errors-reference"
                    }
                  },
                  "Survey does not exists": {
                    "value": {
                      "statusCode": 400,
                      "error": "Bad Request",
                      "message": "Survey does not exists",
                      "code": 241,
                      "docs": "https://github.com/DiegoVictor/npser#errors-reference"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
  },
  "components": {
    "schemas": {
      "User": {
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          }
        }
      },
      "Survey": {
        "properties": {
          "id": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          }
        }
      },
      "Answer": {
        "properties": {
          "id": {
            "type": "string"
          },
          "user_id": {
            "type": "string"
          },
          "survey_id": {
            "type": "string"
          },
          "value": {
            "type": "integer"
          },
          "created_at": {
            "type": "string"
          },
          "user": {
            "$ref": "#/components/schemas/User"
          },
          "survey": {
            "$ref": "#/components/schemas/Survey"
          }
        }
      },
      "Error": {
        "properties": {
          "statusCode": {
            "type": "integer"
          },
          "error": {
            "type": "string"
          },
          "message": {
            "type": "string"
          },
          "code": {
            "type": "integer"
          },
          "docs": {
            "type": "string"
          }
        }
      }
    }
  }
}
